### ISSUE TITLE
Add action button

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-toast#10]
# User story

As a user using the toast component, I want to be able to click on the action button or click anywhere on the toast, so I can dismiss the toast.

### Specific steps required to deliver this work.

- [ ] Add action icon button on the right side of the toast
- [ ] Add a function to handle when the button is clicked on
- [ ] use the same onclick function from the action button to dismiss the toast when the user clicks anywhere on the toast

## Definition of “Done” (exit criteria)
The story is “done” when the reviewer can validate the outlined tasks and UI matches the expectations of the designed element spec. 

- https://github.com/AlaskaAirlines/auro-toast/issues/1

#### Has been tested in all browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [ ] Safari
- [ ] Mobile Safari

#### Has been tested for accessibility

- [ ] Axe / Google Lighthouse (baseline standard)
- [ ] Screenreader (determine usability of experience via screenreader)
- [ ] Keyboard use (a user must be able to navigate to key parts via a keyboard)

#### Auro component features

- [ ] README doc completed with all relative information
- [ ] API documentation created
- [ ] Bundled version tested and documented
- [ ] Examples and use case info created
- [ ] Demo page created for the Auro Doc Site

**Comment by cynthiaricomendoza-alaskaair** [comment]
@leeejune as i'm looking at this, can we simplify this a bit for MVP by choosing one way to dismiss the toast across both mobile and desktop? what do you think about only closing the toast when the action icon button is clicked on? (pushing the mobile "touch target is entire toast" to the backlog)

the reason i bring this up is because i really haven't seen any examples of toasts where if the user clicks anywhere on the toast it gets dismissed. i only see examples of the toast dismissing itself after X amount of seconds OR the toast is dismissed by clicking some sort of X icon action button.

**Comment by leeejune** [comment]
@cynthiaricomendoza-alaskaair If it delays development significantly, I don't mind us leaving it as a future feature. The design decision came from the intention of increasing the touch target on mobile since it might be harder to find the "x" and press on it.
