### ISSUE TITLE
Close toast after 5 seconds

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-toast#13]
# User story

As a user using the toast component, I want to be able to see the toast get dismissed on its own after 5 seconds, so I can I don't have to dismiss it myself.

### Specific steps required to deliver this work.
- [ ] Include appropriate animation for toast dismissal
- [ ] Add function to automatically close toast if there is not user interaction after 5 seconds

## Definition of “Done” (exit criteria)
The story is “done” when the reviewer can validate the outlined tasks and UI matches the expectations of the designed element spec. 

- https://github.com/AlaskaAirlines/auro-toast/issues/1

#### Has been tested in all browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [ ] Safari
- [ ] Mobile Safari

#### Has been tested for accessibility

- [ ] Axe / Google Lighthouse (baseline standard)
- [ ] Screenreader (determine usability of experience via screenreader)
- [ ] Keyboard use (a user must be able to navigate to key parts via a keyboard)

#### Auro component features

- [ ] README doc completed with all relative information
- [ ] API documentation created
- [ ] Bundled version tested and documented
- [ ] Examples and use case info created
- [ ] Demo page created for the Auro Doc Site

**Comment by cynthiaricomendoza-alaskaair** [comment]
for this first initial version of the toast, we would like to set the duration to 5 seconds for all use cases. at a later time, we can bring in the +1 second for every 120 seconds. will discuss with @leeejune

**Comment by leeejune** [comment]
Yup, for the MVP we can have a default duration as 5 seconds. We should just make sure to create another issue to track the "+1 sec for every 120 char" feature.
