### ISSUE TITLE
auro-toast: Flexibility to choose icon, background color, and not have it auto-dismiss

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-toast#53]
### Is your feature request related to a problem? Please describe.

I was recommended by auro designers to use toast for a dismissible popup containing minimal text, that the guest would have to dismiss themselves. But the current version doesn't meet all my needs, nor do any of the other components available to me.

Example:
![image](https://github.com/user-attachments/assets/8d832f66-a035-4e38-a207-00a88065eb82)

### Describe the solution you'd like

I would like to be able to make a personalized toast, outside of the current success/default/warning/info options, where we could select any auro icon (or subset of auro icons) along with using any of our container/background color tokens. The ability to have it auto-dismiss, or not, would also be beneficial.

### Describe alternatives you've considered

Auro dialog specs are too large for my use case, and popup only appears on hover/click. We want this there upon landing on a page.

**Comment by Patrick-Daly-AA** [comment]
Will need to validate that text content for a toast is in a slot and can be customized.

Also that visible attribute can be set manually to over-ride the auto-dismissal timer.  If that isn't the case, we will need to consider exposing a customizable auto-dismiss time attribute.
