### ISSUE TITLE
Add "variant" property

### ISSUE THREAD

**Issue by cynthiaricomendoza-alaskaair** [AlaskaAirlines/auro-toast#8]
# User story

This story must come before [this one](https://github.com/AlaskaAirlines/auro-toast/issues/9)

As a user using the toast component, I want to be able to indicate if I want a success or error toast, so I can display the toast accordingly.

### Specific steps required to deliver this work.
- [ ] variant should be an enum with "success" and "error"
- [ ] When no type is defined in component, the background color of the component (see auro-alert for specific gray color)
- [ ] When type is defined as success in component, the background color of the component should be green (#DDF6E8)
- [ ] When type is defined as error in component, the background color of the component should be red (#FFEDF1)

## Definition of “Done” (exit criteria)
The story is “done” when the reviewer can validate the outlined tasks and UI matches the expectations of the designed element spec. 

- https://github.com/AlaskaAirlines/auro-toast/issues/1

#### Has been tested in all browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge (79 +)
- [ ] Safari
- [ ] Mobile Safari

#### Has been tested for accessibility

- [ ] Axe / Google Lighthouse (baseline standard)
- [ ] Screenreader (determine usability of experience via screenreader)
- [ ] Keyboard use (a user must be able to navigate to key parts via a keyboard)

#### Auro component features

- [ ] README doc completed with all relative information
- [ ] API documentation created
- [ ] Bundled version tested and documented
- [ ] Examples and use case info created
- [ ] Demo page created for the Auro Doc Site

**Comment by cynthiaricomendoza-alaskaair** [comment]
will discuss with @leeejune about what background color to use for the default use case

**Comment by leeejune** [comment]
Updated blueprint with a default state: https://www.figma.com/file/NdpGKlGb2ammFV7eakNa8Z/Toast?type=design&node-id=322-298&t=4PzILxMUDQ3TiIWN-11

![Screenshot 2023-05-19 at 11 16 13 AM](https://github.com/AlaskaAirlines/auro-toast/assets/55998746/9e3ebf89-877d-4803-8888-d90b65a69885)

**Comment by cynthiaricomendoza-alaskaair** [comment]
@leeejune Dale pointed out in my PR that we shouldn't be using direct values for colors, which is what i was doing for the background color of the success and error toast. he mentioned we should be using auro design tokens. i found this red color that matches the blueprint `var(--auro-color-brand-flamingo-100)`. however, i wasn't able to find a color to match the green color from the blueprint. do you have any suggestions on what auro color we should be using for the success background color?

**Comment by leeejune** [comment]
@cynthiaricomendoza-alaskaair The background colors should be added through this issue: https://github.com/AlaskaAirlines/AuroDesignTokens/issues/100

@braven112 are there any updates on this?
